/*.$file${../qm_generated::dishwasher_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_qpn_pio.qm
* File:  ${../qm_generated::dishwasher_sm.c}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::dishwasher_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "dishwasher_sm.h"
#include "bsp.h"
#include "app/dishwasher_helpers.h"

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Dishwasher} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Dishwasher} ..........................................................*/
/*.${AOs::Dishwasher::SM} ......................................................*/
QState Dishwasher_initial(Dishwasher * const me) {
    /*.${AOs::Dishwasher::SM::initial} */
    Dishwasher_armTimeout((QActive *) me);
    return Q_TRAN(&Dishwasher_off);
}
/*.${AOs::Dishwasher::SM::off} .................................................*/
QState Dishwasher_off(Dishwasher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*.${AOs::Dishwasher::SM::off} */
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::Dishwasher::SM::off::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Dishwasher_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::Dishwasher::SM::on} ..................................................*/
QState Dishwasher_on(Dishwasher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*.${AOs::Dishwasher::SM::on} */
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::Dishwasher::SM::on::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Dishwasher_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::Dishwasher} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
