/*.$file${../qm_generated::heater_sm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_controller.qm
* File:  ${../qm_generated::heater_sm.h}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::heater_sm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef HEATER_SM_H
#define HEATER_SM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "qpn.h"
#include "signals.h"
#include "constants.h"
#include "active_objects.h"

/*.$declare${AOs::Heater} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Heater} ..........................................................*/
typedef struct Heater {
/* protected: */
    QActive super;
} Heater;

/* protected: */
QState Heater_initial(Heater * const me);
QState Heater_Operating(Heater * const me);
QState Heater_Heating(Heater * const me);
QState Heater_HeatingInner(Heater * const me);
QState Heater_NotHeating(Heater * const me);
QState Heater_NotHeatingInner(Heater * const me);
QState Heater_Fault(Heater * const me);
/*.$enddecl${AOs::Heater} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef __cplusplus
}
#endif

#endif