/*$file${../qm_generated::heater_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_controller.qm
* File:  ${../qm_generated::heater_sm.c}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../qm_generated::heater_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "heater_sm.h"
#include "bsp.h"
#include "app/heater_helpers.h"

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Heater} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Heater} ...........................................................*/

/*${AOs::Heater::SM} .......................................................*/
QState Heater_initial(Heater * const me) {
    /*${AOs::Heater::SM::initial} */
    return Q_TRAN(&Heater_Operating);
}

/*${AOs::Heater::SM::Operating} ............................................*/
QState Heater_Operating(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Heater_NotHeating);
            break;
        }
        /*${AOs::Heater::SM::Operating::FAULT} */
        case FAULT_SIG: {
            status_ = Q_TRAN(&Heater_Fault);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Heater::SM::Operating::Heating} ...................................*/
QState Heater_Heating(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::Heating} */
        case Q_ENTRY_SIG: {
            Heater_startHeating();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Heater::SM::Operating::Heating} */
        case Q_EXIT_SIG: {
            Heater_stopHeating();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Heater_Operating);
            break;
        }
    }
    return status_;
}

/*${AOs::Heater::SM::Operating::Heating::HeatingInner} .....................*/
QState Heater_HeatingInner(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::Heating::HeatingInner} */
        case Q_ENTRY_SIG: {
            QActive_armX(&me->super, 0U, HEAT_LOOP_TIMEOUT_TICKS, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Heater::SM::Operating::Heating::HeatingInner::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            /*${AOs::Heater::SM::Operating::Heating::HeatingInner::Q_TIMEOUT::[Heater_shouldHeatStayOn()]} */
            if (Heater_shouldHeatStayOn()) {
                status_ = Q_TRAN(&Heater_HeatingInner);
            }
            /*${AOs::Heater::SM::Operating::Heating::HeatingInner::Q_TIMEOUT::[else]} */
            else {
                status_ = Q_TRAN(&Heater_NotHeatingInner);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Heater_Heating);
            break;
        }
    }
    return status_;
}

/*${AOs::Heater::SM::Operating::NotHeating} ................................*/
QState Heater_NotHeating(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::NotHeating} */
        case Q_ENTRY_SIG: {
            Heater_stopHeating();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Heater::SM::Operating::NotHeating::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Heater_NotHeatingInner);
            break;
        }
        default: {
            status_ = Q_SUPER(&Heater_Operating);
            break;
        }
    }
    return status_;
}

/*${AOs::Heater::SM::Operating::NotHeating::NotHeatingInner} ...............*/
QState Heater_NotHeatingInner(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::NotHeating::NotHeatingInner} */
        case Q_ENTRY_SIG: {
            QActive_armX(&me->super, 0U, HEAT_LOOP_TIMEOUT_TICKS, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Heater::SM::Operating::NotHeating::NotHeatingInner::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            /*${AOs::Heater::SM::Operating::NotHeating::NotHeatingInner::Q_TIMEOUT::[Heater_shouldHeatStayOff()]} */
            if (Heater_shouldHeatStayOff()) {
                status_ = Q_TRAN(&Heater_NotHeatingInner);
            }
            /*${AOs::Heater::SM::Operating::NotHeating::NotHeatingInner::Q_TIMEOUT::[else]} */
            else {
                status_ = Q_TRAN(&Heater_HeatingInner);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Heater_NotHeating);
            break;
        }
    }
    return status_;
}

/*${AOs::Heater::SM::Operating::Fault} .....................................*/
QState Heater_Fault(Heater * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Heater::SM::Operating::Fault} */
        case Q_ENTRY_SIG: {
            Heater_stopHeating();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Heater_Operating);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Heater} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
