/*$file${../qm_generated::heater_sm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: dishwasher_controller.qm
* File:  ${../qm_generated::heater_sm.h}
*
* This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../qm_generated::heater_sm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef HEATER_SM_H
#define HEATER_SM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "qpn.h"
#include "signals.h"
#include "constants.h"
#include "active_objects.h"

/*$declare${AOs::Heater} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Heater} ...........................................................*/
typedef struct Heater {
/* protected: */
    QActive super;
} Heater;

/* protected: */
QState Heater_initial(Heater * const me);
QState Heater_Operating(Heater * const me);
QState Heater_Heating(Heater * const me);
QState Heater_HeatingInner(Heater * const me);
QState Heater_NotHeating(Heater * const me);
QState Heater_NotHeatingInner(Heater * const me);
QState Heater_Fault(Heater * const me);
/*$enddecl${AOs::Heater} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef __cplusplus
}
#endif

#endif
